<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<div id="side-menu">
			<table>
				<tr>
					<td>글쓰기</td>
				</tr>
				<tr>
					<td>전체글보기</td>
				</tr>
				<tr>
					<td>게시물검색(작성자)</td>
				</tr>
				<tr>
					<td>게시물검색(글번호)</td>
				</tr>
				<tr>
					<td>총게시물수</td>
				</tr>
				<tr>
					<td>게시물확인</td>
				</tr>
				<tr>
					<td>게시물수정</td>
				</tr>
				<tr>
					<td>게시물삭제</td>
				</tr>
			</table>
			</div>